import { defineConfig } from "orval";

/**
 * Generates the typed API client from the backend's OpenAPI contract.
 *
 * The spec in api/openapi.json is a committed snapshot of the backend's
 * docs/openapi.json. Refresh it with `npm run sync:api` (which pulls from a
 * running backend), then regenerate with `npm run generate:api`.
 *
 * Generated output is committed so CI and Vercel builds never need to reach a
 * backend. Do not edit anything under lib/api/generated by hand.
 */
export default defineConfig({
  animalFamily: {
    input: "./api/openapi.json",
    output: {
      target: "./lib/api/generated/client.ts",
      schemas: "./lib/api/generated/model",
      client: "react-query",
      httpClient: "fetch",
      mode: "tags-split",
      clean: true,
      // Takes the /api/v2 prefix from the spec's `servers` entry, so the path
      // lives in the contract rather than being duplicated in this config.
      baseUrl: { getBaseUrlFromSpecification: true },
      override: {
        // Routes every request through one function so the auth header, base
        // URL and error handling live in a single place, rather than being
        // re-implemented in each hook the way the hand-written lib/api/*.ts
        // files did.
        mutator: {
          path: "./lib/api/fetcher.ts",
          name: "apiFetch",
        },
        // Only `signal` is overridden here. Setting useQuery/useMutation
        // explicitly overrides orval's method-based defaults and inverts them,
        // generating mutation options for GETs and query options for POSTs.
        query: {
          signal: true,
        },
      },
    },
  },
});
